### ISSUE TITLE
No module named 'datasets' on Outlines 0.1.9

### ISSUE THREAD

**Issue by cpfiffer** [dottxt-ai/outlines#1332]
### Describe the issue as clearly as possible:

Running Outlines code on a few of the latest versions (above 0.1.6, I believe) can induce an error with the transformers backend, due to `datasets` not being installed.

I was able to run this on 0.1.6 with no issues, but 0.1.9 and possibly others between will fail.

### Steps/code to reproduce the bug:

```python
import outlines
import transformers
from pydantic import BaseModel

model = outlines.models.transformers(
    "HuggingFaceTB/SmolLM2-135M-Instruct",
    device="auto",
)

class Testing(BaseModel):
    name: str
    age: int

generator = outlines.generate.json(model, Testing)

print(generator("Who is that one person that I know?"))
```

### Expected result:

```shell
Testing[name='Monica' age=27]
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/mwe.py", line 14, in <module>
    generator = outlines.generate.json(model, Testing)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines/generate/json.py", line 51, in json
    generator = regex(model, regex_str, sampler)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines/generate/regex.py", line 34, in regex
    logits_processor = RegexLogitsProcessor(regex_str, tokenizer=model.tokenizer)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines/processors/structured.py", line 153, in __init__
    guide = RegexGuide.from_regex(regex_string, tokenizer)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines/fsm/guide.py", line 92, in from_regex
    return super().from_regex(
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines_core/fsm/guide.py", line 212, in from_regex
    ) = _create_states_mapping(
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines/fsm/guide.py", line 76, in cached_create_states_mapping
    return uncached_create_states_mapping(regex_string, tokenizer, *args, **kwargs)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines_core/fsm/guide.py", line 141, in create_states_mapping
    return create_states_mapping_from_fsm(regex_fsm, tokenizer, frozen_tokens)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines_core/fsm/guide.py", line 178, in create_states_mapping_from_fsm
    states_to_token_maps, empty_token_ids = create_fsm_index_tokenizer(
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines_core/fsm/regex.py", line 473, in create_fsm_index_tokenizer
    tokens_to_token_ids, empty_token_ids = reduced_vocabulary(tokenizer)
  File "/home/cameron/dottxt/demos/holidays-2024/gifter/.pyron/lib/python3.10/site-packages/outlines/models/transformers.py", line 117, in __hash__
    from datasets.fingerprint import Hasher
ModuleNotFoundError: No module named 'datasets'
```

### Outlines/Python version information:

Version information when using Outlines 0.1.19 (broken)
<details>
```
accelerate==1.2.0
airportsdata==20241001
annotated-types==0.7.0
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.4.0
cloudpickle==3.1.0
diskcache==5.6.3
filelock==3.16.1
fsspec==2024.10.0
huggingface-hub==0.26.5
idna==3.10
interegular==0.3.3
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
lark==1.2.2
MarkupSafe==3.0.2
mpmath==1.3.0
nest-asyncio==1.6.0
networkx==3.4.2
numpy==2.2.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.1.105
outlines==0.1.9
outlines_core==0.1.24
packaging==24.2
psutil==6.1.0
pycountry==24.6.1
pydantic==2.10.3
pydantic_core==2.27.1
PyYAML==6.0.2
referencing==0.35.1
regex==2024.11.6
requests==2.32.3
rpds-py==0.22.3
safetensors==0.4.5
sympy==1.13.3
tokenizers==0.21.0
torch==2.4.0
tqdm==4.67.1
transformers==4.47.0
triton==3.0.0
typing_extensions==4.12.2
urllib3==2.2.3
```
</details>

Version information when using Outlines 0.1.16 (works)
<details>
```
accelerate==1.2.0
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.1
airportsdata==20241001
annotated-types==0.7.0
async-timeout==5.0.1
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.4.0
cloudpickle==3.1.0
datasets==3.2.0
dill==0.3.8
diskcache==5.6.3
filelock==3.16.1
frozenlist==1.5.0
fsspec==2024.9.0
huggingface-hub==0.26.5
idna==3.10
interegular==0.3.3
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
lark==1.2.2
MarkupSafe==3.0.2
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.16
nest-asyncio==1.6.0
networkx==3.4.2
numpy==2.2.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.1.105
outlines==0.1.6
outlines_core==0.1.17
packaging==24.2
pandas==2.2.3
propcache==0.2.1
psutil==6.1.0
pyarrow==18.1.0
pycountry==24.6.1
pydantic==2.10.3
pydantic_core==2.27.1
python-dateutil==2.9.0.post0
pytz==2024.2
PyYAML==6.0.2
referencing==0.35.1
regex==2024.11.6
requests==2.32.3
rpds-py==0.22.3
safetensors==0.4.5
six==1.17.0
sympy==1.13.3
tokenizers==0.21.0
torch==2.4.0
tqdm==4.67.1
transformers==4.47.0
triton==3.0.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
xxhash==3.5.0
yarl==1.18.3
```
</details>

**Comment by rlouf** [comment]
`pip install outlines[transformers]`

**Comment by cpfiffer** [comment]
Ah, okay. This works! 

In case anyone else stumbles on this, Outlines cleaned up some unneeded dependencies, and the prior behavior of

```
pip install transformers outlines ...
```

will likely not work for you. Do as Remi suggests and install the Outlines transformer extra correctly:

```
pip install outlines[transformers]
```

**Comment by TimZaman** [comment]
+1 same issue, not great ux. First time user of dottxt, i run the basic example script and ran into this, just FYI. Works now!
